version: '2'

services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: thermostat
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thermostat_development
  web:
    build:
      context: .
      dockerfile: infrastructure/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
    env_file: .env
    volumes:
      - ./:/usr/src/app
    links:
      - db
    ports:
      - "3000:3000"
